### PR TITLE
Added minification for production build

### PR DESCRIPTION
**Pull request by glebmachine**
Issue #47

### CODE REVIEW

**Comment by alexpods** [comment]
@glebmachine I'm going to merge this PR. Just one question:

What's the point of `es-promise`, `es-shim` and `reflect-metadata`? `core-js` covers all of these (see [here](https://github.com/alexpods/angular2-universal-starter/blob/master/src/polyfills.ts)). Have I missed something?

**Comment by glebmachine** [comment]
Hm, sorry, my previous build don't want to compiled without this.

Let me check again, will remove if unnecessary

**Comment by alexpods** [comment]
ok, cool

**Comment by glebmachine** [comment]
@alexpods Done!

**Comment by alexpods** [comment]
@glebmachine Merged. + added a bunch of tests for minification to travis (see [here](https://github.com/alexpods/angular2-universal-starter/blob/master/.travis.yml#L28))

**Comment by glebmachine** [comment]
Yeah, next PR will be covered by tests, sorry)

**Comment by alexpods** [comment]
No worries. I'm glad to any contribution, it doesnt have any matter if it's with tests or without.

**Pull request merged**
